version: '3'

services:
    selenium-hub:
        image: selenium/hub
        container_name: selenium-hub
        ports:
          - "4444:4444"

    chrome:
        image: selenium/node-chrome-debug
        depends_on:
          - selenium-hub
        volumes:
          - /dev/shm:/dev/shm
        shm_size: "2gb"
        environment:
          - HUB_PORT_4444_TCP_ADDR=selenium-hub 
          - HUB_PORT_4444_TCP_PORT=4444

    python:
        build: .
        container_name: python
        volumes: 
            - .:/app
        command: /bin/bash
        tty: true
        stdin_open: true